language: node_js
os: linux
node_js:
  - 12.22
install:
  - npm install
script:
  - "npm run lint"
  - "npm run prettify"
branches:
  only:
    - build
deploy:
  app: vuttr-api
  provider: heroku
  strategy: api
  api_key:
    secure: $HEROKU_TOKEN