language: node_js
node_js:
  - 12.22
install:
  - npm install
script:
  - "npm run lint"
  - "npm run prettify"
branches:
  only:
    - master
deploy:
  app: vuttr-api
  provider: heroku
  api_key:
    secure: 35df0ca5-ec2d-4cc0-b1d4-839d5bb063f3