export enum NEW_ENTRY_ERRORS {
  GENERIC = "GENERIC ERROR",
  TOOL_NOT_FOUND = "TOOL_NOT_FOUND",
  ID_NOT_VALID = "ID_NOT_VALID",
}

export const newEntryErrorsCodes: { [key: string]: NEW_ENTRY_ERRORS } = {
  GENERIC: NEW_ENTRY_ERRORS.GENERIC,
  TOOL_NOT_FOUND: NEW_ENTRY_ERRORS.TOOL_NOT_FOUND,
  ID_NOT_VALID: NEW_ENTRY_ERRORS.ID_NOT_VALID,
};
