export enum NEW_ENTRY_ERRORS {
  GENERIC = "GENERIC_ERROR",
  TOOL_NOT_FOUND = "TOOL_NOT_FOUND",
  ID_NOT_VALID = "ID_NOT_VALID",
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
  USER_EMAIL_NOT_FOUND = "USER_EMAIL_NOT_FOUND",
  TOKEN_NO_PROVIDER = "TOKEN_NO_PROVIDER",
  UNAUTHORIZED = "UNAUTHORIZED",
}

export const newEntryErrorsCodes: { [key: string]: NEW_ENTRY_ERRORS } = {
  GENERIC: NEW_ENTRY_ERRORS.GENERIC,
  TOOL_NOT_FOUND: NEW_ENTRY_ERRORS.TOOL_NOT_FOUND,
  ID_NOT_VALID: NEW_ENTRY_ERRORS.ID_NOT_VALID,
  EMAIL_ALREADY_REGISTERED: NEW_ENTRY_ERRORS.EMAIL_ALREADY_REGISTERED,
  USER_EMAIL_NOT_FOUND: NEW_ENTRY_ERRORS.USER_EMAIL_NOT_FOUND,
  TOKEN_NO_PROVIDER: NEW_ENTRY_ERRORS.TOKEN_NO_PROVIDER,
  UNAUTHORIZED: NEW_ENTRY_ERRORS.UNAUTHORIZED,
};
